// flow-typed signature: 814a59e1e68c885ae455102c85dc68aa
// flow-typed version: <<STUB>>/tachyons-cli_v^1.2.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tachyons-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tachyons-cli/cli.js' {
  declare module.exports: $Exports<'tachyons-cli/cli'>;
}
